require 'helper'

class TestKindleDrm < Test::Unit::TestCase

  should "generate Personal ID (PID) strings correctly" do	
	# Valid test output generated by original Python code.
	assert_equal crc32('aoeuaoeuaoeuaoeu'), 593220825
	assert_equal serialToIntermediaryPid('aoeuaoeuaoeuaoeu', 7), "RB5MXY5"
	assert_equal checksumPid('aoeuaoeuaoeuaoeu'), "aoeuaoeuaoeuaoeu7P"
	assert_equal checksumPid('RB5MXY5'), "RB5MXY5LR"
	assert_equal serialToPid('B001DEADBABECAFE'), 'RB6IUSR*MU'
  end

end
